spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.sql: debug
